###
GET http://localhost:8080/jobs

### simple-job
GET http://localhost:8080/jobs/simple-job
    ?name={{$random.alphanumeric(8)}}

### schedule-simple-job
GET http://localhost:8080/jobs/schedule-simple-job
    ?name={{$random.alphanumeric(8)}}
    &when=PT20S

### long-running-job
GET http://localhost:8080/jobs/long-running-job
    ?name={{$random.alphanumeric(8)}}

### long-running-job-with-job-context
GET http://localhost:8080/jobs/long-running-job-with-job-context
    ?name={{$random.alphanumeric(8)}}

